### ISSUE TITLE
What's the Matter Here ?!!

### ISSUE THREAD

**Issue by Kadantte** [c0tangent/sadpandabot#1]
Traceback (most recent call last):
  File "sadpandabot.py", line 10, in <module>
    DISCORD_TOKEN = os.environ['DISCORD_TOKEN']
  File "C:\Users\HOTD\AppData\Local\Programs\Python\Python35-32\lib\os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISCORD_TOKEN'

**Comment by Kadantte** [comment]
Fix it.
